/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author franc
 */
public class CompararHammingPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompararHammingPanel
     */
    public CompararHammingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        textoArchivoTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        abrirAButton2 = new javax.swing.JButton();
        textoArchivoTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);

        jLabel3.setText("Seleccionar archivo: ");

        abrirAButton2.setText("Abrir Archivo");
        abrirAButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButton2MousePressed(evt);
            }
        });
        abrirAButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButton2ActionPerformed(evt);
            }
        });

        textoArchivoTextArea2.setColumns(20);
        textoArchivoTextArea2.setRows(5);

        jLabel1.setText("Comparar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abrirAButton))
                    .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abrirAButton2))
                    .addComponent(textoArchivoTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(472, 472, 472))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(abrirAButton2))
                        .addGap(22, 22, 22)
                        .addComponent(textoArchivoTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(abrirAButton))
                        .addGap(22, 22, 22)
                        .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected =true;
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            try {
                String s = "", cadena = "";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    s += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextArea.setText(s);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonMousePressed

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed

    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void abrirAButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButton2MousePressed

    private void abrirAButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton abrirAButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea textoArchivoTextArea;
    private javax.swing.JTextArea textoArchivoTextArea2;
    // End of variables declaration//GEN-END:variables
}
