/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Hamming.HammingProcessor;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.DefaultHighlighter.DefaultHighlightPainter;
import javax.swing.text.Highlighter;
import java.awt.*;
import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author franc
 */
public class CompararHammingPanel extends Panel{

    private String path,name,path2,name2,text1,text2;
    private boolean selected,selected2;
    File file,file2;
    private HammingProcessor hm;
    /**
     * Creates new form ProtegerPanel
     */

    @Override
    public void init() {
        textoArchivoTextPane1.setText("");
        textoArchivoTextPane2.setText("");
        path="";
        name="";
        name2="";
        path2="";
        text1="";
        text2="";
        file=null;
        file2=null;
        selected=false;
        selected2=false;
    }

    private boolean validExtension(String extension) {
        boolean result = false;
        Pattern pattern = Pattern.compile("^h([ae])[0-9]$");
        Matcher matcher = pattern.matcher(extension);
        if (matcher.matches()) {
            result = true;
        }
        return result;
    }

    private boolean validFiles(String filename, String filename2){
        boolean result = false;
        String aux = filename.substring(filename.lastIndexOf('.')-2,filename.lastIndexOf('.'));
        String aux2 = filename2.substring(filename2.lastIndexOf('.')-2,filename2.lastIndexOf('.'));
        if (filename.substring(0,filename.lastIndexOf('.')).equals(filename2.substring(0,filename2.lastIndexOf('.')))){
            if(validExtension(filename.substring(filename.lastIndexOf('.'))) || validExtension(filename2.substring(filename2.lastIndexOf('.')))){
                result = true;
            }
            Pattern pattern1 = Pattern.compile("^[SC]E$");
            Matcher matcher1 = pattern1.matcher(aux);
            Matcher matcher2 = pattern1.matcher(aux2);
            if (matcher1.matches() && matcher2.matches()) {
                result = true;
            }
        }

        return result;
    }

    /**
     * Creates new form CompararHammingPanel
     */
    public CompararHammingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        abrirAButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArchivoTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoArchivoTextPane1 = new javax.swing.JTextPane();

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccionar archivo: ");

        abrirAButton2.setText("Abrir Archivo");
        abrirAButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButton2MousePressed(evt);
            }
        });
        abrirAButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPARAR");

        jScrollPane1.setViewportView(textoArchivoTextPane2);

        jScrollPane3.setViewportView(textoArchivoTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76)
                        .addComponent(abrirAButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76)
                        .addComponent(abrirAButton2)))
                .addGap(68, 68, 68))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(abrirAButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(abrirAButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser("./");
        int r = j.showSaveDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            try {
                String  cadena = "";
                text1="";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text1 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextPane1.setText(text1);
                selected =true;
                if(selected2){
                    Highlighter.HighlightPainter hp = new DefaultHighlightPainter(Color.red);
                    char[] auxtext1 = text1.toCharArray();
                    char[] auxtext2 = text2.toCharArray();
                    for (int i =0 ; i< auxtext1.length;i++){
                        if(auxtext1[i]!= auxtext2[i]){
                            textoArchivoTextPane2.getHighlighter().addHighlight(i,i+1,hp);
                        }
                        System.out.println(i);
                    }
                }
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            } catch (BadLocationException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonMousePressed

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed

    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void abrirAButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButton2MousePressed
        JFileChooser j = new JFileChooser("./");
        int r = j.showSaveDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected2 =true;
            path2 = j.getSelectedFile().getAbsolutePath();
            file2= new File(path2);
            name2 = j.getSelectedFile().getName();
            name2= name2.substring(0, name2.lastIndexOf('.'));
            try {
                String  cadena = "";
                text2="";
                FileReader f = new FileReader(path2);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text2 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextPane2.setText(text2);

                if (selected){
                    Highlighter.HighlightPainter hp = new DefaultHighlightPainter(Color.red);
                    char[] auxtext1 = text1.toCharArray();
                    char[] auxtext2 = text2.toCharArray();
                    for (int i =0 ; i< auxtext1.length;i++){
                        if(auxtext1[i]!= auxtext2[i]){
                            textoArchivoTextPane2.getHighlighter().addHighlight(i,i+1,hp);
                        }
                        System.out.println(i);
                    }
                }
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            } catch (BadLocationException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected2 = false;
        }
    }//GEN-LAST:event_abrirAButton2MousePressed

    private void abrirAButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton abrirAButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane textoArchivoTextPane1;
    private javax.swing.JTextPane textoArchivoTextPane2;
    // End of variables declaration//GEN-END:variables
}
