/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Hamming.HammingProcessor;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author franc
 */
public class CompararHammingPanel extends Panel{

    private String path,name,path2,name2,text1,text2;
    private boolean selected,selected2;
    File file,file2;
    private HammingProcessor hm;
    /**
     * Creates new form ProtegerPanel
     */

    @Override
    public void init() {
        textoArchivoTextArea.setText("");
        selected=false;
        selected2=false;
    }

    private boolean validExtension(String extension) {
        boolean result = false;
        Pattern pattern = Pattern.compile("^h([ae])[0-9]$");
        Matcher matcher = pattern.matcher(extension);
        if (matcher.matches()) {
            result = true;
        }
        return result;
    }

    private boolean validFiles(String filename, String filename2){
        boolean result = false;
        String aux = filename.substring(filename.lastIndexOf('.')-2,filename.lastIndexOf('.'));
        String aux2 = filename2.substring(filename2.lastIndexOf('.')-2,filename2.lastIndexOf('.'));
        if (filename.substring(0,filename.lastIndexOf('.')).equals(filename2.substring(0,filename2.lastIndexOf('.')))){
            if(validExtension(filename.substring(filename.lastIndexOf('.'))) || validExtension(filename2.substring(filename2.lastIndexOf('.')))){
                result = true;
            }
            Pattern pattern1 = Pattern.compile("^[SC]E$");
            Matcher matcher1 = pattern1.matcher(aux);
            Matcher matcher2 = pattern1.matcher(aux2);
            if (matcher1.matches() && matcher2.matches()) {
                result = true;
            }
        }

        return result;
    }

    /**
     * Creates new form CompararHammingPanel
     */
    public CompararHammingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        textoArchivoTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        abrirAButton2 = new javax.swing.JButton();
        textoArchivoTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);

        jLabel3.setText("Seleccionar archivo: ");

        abrirAButton2.setText("Abrir Archivo");
        abrirAButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButton2MousePressed(evt);
            }
        });
        abrirAButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButton2ActionPerformed(evt);
            }
        });

        textoArchivoTextArea2.setColumns(20);
        textoArchivoTextArea2.setRows(5);

        jLabel1.setText("Comparar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abrirAButton))
                    .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abrirAButton2))
                    .addComponent(textoArchivoTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(472, 472, 472))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(abrirAButton2))
                        .addGap(22, 22, 22)
                        .addComponent(textoArchivoTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(abrirAButton))
                        .addGap(22, 22, 22)
                        .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected =true;
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            try {
                String  cadena = "";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text1 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextArea2.setText(text1);
                if(selected2){

                }
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonMousePressed

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected2 =true;
            path2 = j.getSelectedFile().getAbsolutePath();
            file2= new File(path);
            name2 = j.getSelectedFile().getName();
            name2= name2.substring(0, name2.lastIndexOf('.'));
            try {
                String  cadena = "";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text2 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextArea.setText(text2);

                if (selected){

                }
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void abrirAButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButton2MousePressed

    }//GEN-LAST:event_abrirAButton2MousePressed

    private void abrirAButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton abrirAButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea textoArchivoTextArea;
    private javax.swing.JTextArea textoArchivoTextArea2;
    // End of variables declaration//GEN-END:variables
}
