/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author franc
 */
public class DesprotegerPanel extends Panel {
    
    private String path,name;
    private boolean selected;
    File file;


    /**
     * Creates new form ProtegerPanel
     */
    public DesprotegerPanel() {
        initComponents();
    }
    @Override
    public void init() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protegerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        textoArchivoTextArea = new javax.swing.JTextArea();
        desprotegerErrorButton = new javax.swing.JButton();
        desprotegerButton = new javax.swing.JButton();

        protegerLabel.setText("Desproteger");

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);

        desprotegerErrorButton.setText("Desproteger c/errores");
        desprotegerErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desprotegerErrorButtonMousePressed(evt);
            }
        });

        desprotegerButton.setText("Desproteger s/errores");
        desprotegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desprotegerButtonMousePressed(evt);
            }
        });
        desprotegerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desprotegerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(protegerLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(abrirAButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(desprotegerErrorButton)
                        .addGap(152, 152, 152)
                        .addComponent(desprotegerButton)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(protegerLabel)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirAButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desprotegerErrorButton)
                    .addComponent(desprotegerButton))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected =true;
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            FileReader f;
            BufferedReader b ;
            try {
                f = new FileReader(new File(path));
                b = new BufferedReader(f);
                String s = "", cadena = "";

                while ((cadena = b.readLine()) != null) {
                    s += cadena + "\n";
                }
                f.close();
                b.close();
                textoArchivoTextArea.setText(s);
            }
            catch (FileNotFoundException ex) {
            Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void desprotegerErrorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerErrorButtonMousePressed
        if(selected){
            Pattern pattern = Pattern.compile("^ha[0-9]$");
            String extension = path.substring(path.lastIndexOf('.')+1);

        }
    }//GEN-LAST:event_desprotegerErrorButtonMousePressed

    private void desprotegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desprotegerButtonMousePressed

    private void desprotegerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desprotegerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desprotegerButtonActionPerformed

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton desprotegerButton;
    private javax.swing.JButton desprotegerErrorButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel protegerLabel;
    private javax.swing.JTextArea textoArchivoTextArea;
    // End of variables declaration//GEN-END:variables

    
    
}
