/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Hamming.HammingProcessor;
import Utils.DoubleErrorException;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;

/**
 * @author franc
 */
public class DesprotegerPanel extends Panel {

    private String path, name;
    private boolean selected;
    File file;
    HammingProcessor hm;


    /**
     * Creates new form ProtegerPanel
     */
    public DesprotegerPanel() {
        initComponents();
        hm = new HammingProcessor();
    }

    @Override
    public void init() {
        textoArchivoTextArea.setText("");
        selected = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protegerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        desprotegerErrorButton = new javax.swing.JButton();
        desprotegerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArchivoTextArea = new javax.swing.JTextArea();

        protegerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        protegerLabel.setText("DESPROTEGER");

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        desprotegerErrorButton.setText("Desproteger c/errores");
        desprotegerErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desprotegerErrorButtonMousePressed(evt);
            }
        });

        desprotegerButton.setText("Desproteger s/errores");
        desprotegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desprotegerButtonMousePressed(evt);
            }
        });
        desprotegerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desprotegerButtonActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);
        jScrollPane1.setViewportView(textoArchivoTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(abrirAButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(desprotegerErrorButton)
                        .addGap(152, 152, 152)
                        .addComponent(desprotegerButton)))
                .addContainerGap(563, Short.MAX_VALUE))
            .addComponent(protegerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protegerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirAButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desprotegerErrorButton)
                    .addComponent(desprotegerButton))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private char validExtension(String extension) {
        char auxChar = 'f';
        Pattern pattern = Pattern.compile("^h([ae])[0-9]$");
        Matcher matcher = pattern.matcher(extension);
        if (matcher.matches()) {
            auxChar = extension.charAt(1);
        }
        return auxChar;
    }

    private void configHm() {
        String extension = path.substring(path.lastIndexOf('.') + 1);
        char auxChar = this.validExtension(extension);
        if (auxChar != 'f') {
            int nBits = Integer.parseInt(extension.substring(extension.lastIndexOf(auxChar)+ 1));
            if (nBits == 1) {
                hm.setBlockSize(8);
            } else if (nBits == 2) {
                hm.setBlockSize(4096);
            } else if (nBits == 3) {
                hm.setBlockSize(65536);
            } else {
                hm.setBlockSize(nBits);
            }
        }
    }

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed

    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void desprotegerErrorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerErrorButtonMousePressed
        if (selected) {
            this.configHm();
            try {
                hm.RDaS(path);
                JOptionPane.showMessageDialog(this, "¡Archivo desprotegido con exito!", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            catch(DoubleErrorException e){
                JOptionPane.showMessageDialog(this,"Se detectaron dos errores en el archivo, el mismo no puede ser desprotegido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_desprotegerErrorButtonMousePressed

    private void desprotegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerButtonMousePressed
        if (selected) {
            this.configHm();
            try {
                hm.RCDaS(path);
                JOptionPane.showMessageDialog(this, "¡Archivo desprotegido con exito!", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            catch(DoubleErrorException e){
                JOptionPane.showMessageDialog(this,"Se detectaron dos errores en el archivo, el mismo no puede ser desprotegido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_desprotegerButtonMousePressed

    private void desprotegerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desprotegerButtonActionPerformed

    }//GEN-LAST:event_desprotegerButtonActionPerformed

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser("./");
        int r = j.showSaveDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            selected = true;
            path = j.getSelectedFile().getAbsolutePath();
            file = new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            FileReader f;
            BufferedReader b;
            try {
                f = new FileReader(new File(path));
                b = new BufferedReader(f);
                String s = "", cadena = "";

                while ((cadena = b.readLine()) != null) {
                    s += cadena + "\n";
                }
                f.close();
                b.close();
                textoArchivoTextArea.setText(s);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            selected = false;

        }
    }//GEN-LAST:event_abrirAButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton desprotegerButton;
    private javax.swing.JButton desprotegerErrorButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel protegerLabel;
    private javax.swing.JTextArea textoArchivoTextArea;
    // End of variables declaration//GEN-END:variables


}
