/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Hamming.HammingProcessor;
import Utils.SMenuGUIHandler;

import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author Usuario
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private Frame() {
        initComponents();
    }

    private static Frame instance;

    public static  Frame getInstance(){
        if (instance==null){
            instance = new Frame();
        }
        return instance;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JPanel();
        HammingButton = new javax.swing.JButton();
        HuffmannButton = new javax.swing.JButton();
        MenuSecundario = new javax.swing.JPanel();
        CardL1 = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        CardL2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HammingButton.setText("Hamming");
        HammingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HammingButtonMousePressed(evt);
            }
        });

        HuffmannButton.setText("Huffmann");
        HuffmannButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HuffmannButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HammingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuffmannButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(HammingButton)
                .addGap(43, 43, 43)
                .addComponent(HuffmannButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuSecundario.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout CardL1Layout = new javax.swing.GroupLayout(CardL1);
        CardL1.setLayout(CardL1Layout);
        CardL1Layout.setHorizontalGroup(
            CardL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        CardL1Layout.setVerticalGroup(
            CardL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        MenuSecundario.add(CardL1, "card2");

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout CardL2Layout = new javax.swing.GroupLayout(CardL2);
        CardL2.setLayout(CardL2Layout);
        CardL2Layout.setHorizontalGroup(
            CardL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CardL2Layout.setVerticalGroup(
            CardL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelPrincipal.add(CardL2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HammingButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HammingButtonMousePressed
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.hammingSecundario);
    }//GEN-LAST:event_HammingButtonMousePressed

    private void HuffmannButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuffmannButtonMousePressed
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.huffmanSecundario);
    }//GEN-LAST:event_HuffmannButtonMousePressed

    public JPanel getMenuSecundario() {
        return MenuSecundario;
    }

    public void setMenuSecundario(JPanel menuSecundario) {
        MenuSecundario = menuSecundario;
    }

    public JPanel getPanelPrincipal() {
        return PanelPrincipal;
    }

    public void setPanelPrincipal(JPanel panelPrincipal) {
        PanelPrincipal = panelPrincipal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()   {
               Frame f1 =Frame.getInstance();
               f1.setVisible(true);
                HammingProcessor hm = new HammingProcessor();
                hm.setBlockSize(4096);
                try {
                    hm.RHaS("fran.txt");
                    hm.RHIEaS("fran.txt",1);
                    hm.RCDaS("fran.hax");
                    hm.RDaS("fran.hax");
                } catch (IOException e) {
                    System.out.println(e.getMessage());
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardL1;
    private javax.swing.JPanel CardL2;
    private javax.swing.JButton HammingButton;
    private javax.swing.JButton HuffmannButton;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel MenuSecundario;
    private javax.swing.JPanel PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
