/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI;

import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.BadLocationException;
import java.io.*;

/**
 *
 * @author franc
 */
public class HammingEstadisticasPanel extends Panel {

    private String path,path2,name2,name,text1,text2;

    private File file,file2;

    private boolean selected,selected2;

    /** Creates new form HammingEstadisticasPanel */
    public HammingEstadisticasPanel() {
        initComponents();
    }
    
    @Override
    public void init() {
        tamanioLabel.setVisible(false);
        tamanioLabel2.setVisible(false);
        tamañoResultLabel.setText("");
        tamañoResultLabel2.setText("");
        redundanciaLabel.setVisible(false);
        redundanciaResultLabel.setText("");
        path="";
        name="";
        name2="";
        path2="";
        text1="";
        text2="";
        file=null;
        file2=null;
        selected=false;
        selected2=false;
        textoArchivoTextPane1.setText("");
        textoArchivoTextPane2.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoArchivoTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArchivoTextPane2 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        abrirAButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tamanioLabel = new javax.swing.JLabel();
        tamanioLabel2 = new javax.swing.JLabel();
        redundanciaLabel = new javax.swing.JLabel();
        tamañoResultLabel = new javax.swing.JLabel();
        tamañoResultLabel2 = new javax.swing.JLabel();
        redundanciaResultLabel = new javax.swing.JLabel();

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(textoArchivoTextPane1);

        textoArchivoTextPane2.setMaximumSize(new java.awt.Dimension(336, 480));
        textoArchivoTextPane2.setMinimumSize(new java.awt.Dimension(336, 480));
        textoArchivoTextPane2.setPreferredSize(new java.awt.Dimension(336, 480));
        jScrollPane1.setViewportView(textoArchivoTextPane2);

        jLabel3.setText("Seleccionar archivo: ");

        abrirAButton2.setText("Abrir Archivo");
        abrirAButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButton2MousePressed(evt);
            }
        });
        abrirAButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTADISTICAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tamanioLabel.setText("Tamaño:");

        tamanioLabel2.setText("Tamaño:");

        redundanciaLabel.setText("Redundancia:");

        tamañoResultLabel.setText("jLabel7");

        tamañoResultLabel2.setText("jLabel8");

        redundanciaResultLabel.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(76, 76, 76)
                            .addComponent(abrirAButton))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tamanioLabel)
                        .addGap(36, 36, 36)
                        .addComponent(tamañoResultLabel)))
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76)
                        .addComponent(abrirAButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tamanioLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(tamañoResultLabel2)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redundanciaLabel)
                .addGap(39, 39, 39)
                .addComponent(redundanciaResultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(abrirAButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(abrirAButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanioLabel)
                    .addComponent(tamanioLabel2)
                    .addComponent(tamañoResultLabel)
                    .addComponent(tamañoResultLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redundanciaLabel)
                    .addComponent(redundanciaResultLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            try {
                String  cadena = "";
                text1="";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text1 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextPane1.setText(text1);
                selected =true;
                tamañoResultLabel.setText(Long.toString(file.length()));
                tamanioLabel.setVisible(true);
                if (selected2){
                    redundanciaLabel.setVisible(true);
                    redundanciaResultLabel.setText(Float.toString((float)file2.length()/(float)file.length()));
                }
                
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonMousePressed

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed

    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void abrirAButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButton2MousePressed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected2 =true;
            path2 = j.getSelectedFile().getAbsolutePath();
            file2= new File(path2);
            name2 = j.getSelectedFile().getName();
            name2= name2.substring(0, name2.lastIndexOf('.'));
            try {
                String  cadena = "";
                text2="";
                FileReader f = new FileReader(path2);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    text2 += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextPane2.setText(text2);
                selected2=true;
                tamañoResultLabel2.setText(Long.toString(file2.length()));
                tamanioLabel2.setVisible(true);
                if (selected){
                    redundanciaLabel.setVisible(true);
                    redundanciaResultLabel.setText(Float.toString((float)file2.length()/(float)file.length()));

                }
            }  catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        else {
            selected2 = false;
        }
    }//GEN-LAST:event_abrirAButton2MousePressed

    private void abrirAButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAButton2ActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JButton abrirAButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel redundanciaLabel;
    private javax.swing.JLabel redundanciaResultLabel;
    private javax.swing.JLabel tamanioLabel;
    private javax.swing.JLabel tamanioLabel2;
    private javax.swing.JLabel tamañoResultLabel;
    private javax.swing.JLabel tamañoResultLabel2;
    private javax.swing.JTextPane textoArchivoTextPane1;
    private javax.swing.JTextPane textoArchivoTextPane2;
    // End of variables declaration//GEN-END:variables

}
