/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Utils.PanelGUIHandler;

/**
 *
 * @author franc
 */
public class HammingSecundario extends Panel {
    
    @Override
    public void init() {
    }

    /**
     * Creates new form HammingSecundario
     */
    public HammingSecundario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protegerButton = new javax.swing.JButton();
        desprotegerButton = new javax.swing.JButton();
        compararButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(78, 217, 255));

        protegerButton.setText("Proteger");
        protegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protegerButtonMousePressed(evt);
            }
        });

        desprotegerButton.setText("Desproteger");
        desprotegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desprotegerButtonMousePressed(evt);
            }
        });

        compararButton.setText("Comparar");
        compararButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                compararButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(protegerButton)
                .addGap(100, 100, 100)
                .addComponent(desprotegerButton)
                .addGap(100, 100, 100)
                .addComponent(compararButton)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(protegerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(desprotegerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compararButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void protegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerButtonMousePressed
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.panelProteger);
    }//GEN-LAST:event_protegerButtonMousePressed

    private void desprotegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerButtonMousePressed
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.panelDesproteger);
    }//GEN-LAST:event_desprotegerButtonMousePressed

    private void compararButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compararButtonMousePressed
        // TODO add your handling code here:
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.panelComparar);
    }//GEN-LAST:event_compararButtonMousePressed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compararButton;
    private javax.swing.JButton desprotegerButton;
    private javax.swing.JButton protegerButton;
    // End of variables declaration//GEN-END:variables
}
