/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Utils.PanelGUIHandler;

/**
 *
 * @author Usuario
 */
public class HuffmanSecundario extends Panel {

    /**
     * Creates new form HuffmanSecundario
     */
    public HuffmanSecundario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompactarButton = new javax.swing.JButton();
        DescompactarButton = new javax.swing.JButton();
        EstadisticasButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(78, 217, 255));

        CompactarButton.setText("Compactar");
        CompactarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompactarButtonMousePressed(evt);
            }
        });
        CompactarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactarButtonActionPerformed(evt);
            }
        });

        DescompactarButton.setText("Descompactar");
        DescompactarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescompactarButtonMousePressed(evt);
            }
        });
        DescompactarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescompactarButtonActionPerformed(evt);
            }
        });

        EstadisticasButton.setText("Estadisticas");
        EstadisticasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EstadisticasButtonMousePressed(evt);
            }
        });
        EstadisticasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(CompactarButton)
                .addGap(100, 100, 100)
                .addComponent(DescompactarButton)
                .addGap(100, 100, 100)
                .addComponent(EstadisticasButton)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompactarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(DescompactarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EstadisticasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CompactarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompactarButtonMousePressed
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.PanelCompactar);
    }//GEN-LAST:event_CompactarButtonMousePressed

    private void DescompactarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescompactarButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescompactarButtonMousePressed

    private void EstadisticasButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasButtonMousePressed

    private void EstadisticasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasButtonActionPerformed
        // TODO add your handling code here:
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.PanelEstadisticas);
    }//GEN-LAST:event_EstadisticasButtonActionPerformed

    private void DescompactarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescompactarButtonActionPerformed
        // TODO add your handling code here:
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.PanelDescompactar);
    }//GEN-LAST:event_DescompactarButtonActionPerformed

    private void CompactarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompactarButtonActionPerformed

    @Override
    public void init() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompactarButton;
    private javax.swing.JButton DescompactarButton;
    private javax.swing.JButton EstadisticasButton;
    // End of variables declaration//GEN-END:variables
}
