/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Utils.PanelGUIHandler;

/**
 *
 * @author Usuario
 */
public class HuffmanSecundario extends Panel {

    /**
     * Creates new form HuffmanSecundario
     */
    public HuffmanSecundario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompactarButton = new javax.swing.JButton();
        DescompactarButton = new javax.swing.JButton();
        CompararButton = new javax.swing.JButton();
        EstadisticasButton = new javax.swing.JButton();

        CompactarButton.setText("Compactar");
        CompactarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompactarButtonMousePressed(evt);
            }
        });

        DescompactarButton.setText("Descompactar");
        DescompactarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescompactarButtonMousePressed(evt);
            }
        });

        CompararButton.setText("Comparar");
        CompararButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompararButtonMousePressed(evt);
            }
        });

        EstadisticasButton.setText("Estadisticas");
        EstadisticasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EstadisticasButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(CompactarButton)
                .addGap(107, 107, 107)
                .addComponent(DescompactarButton)
                .addGap(97, 97, 97)
                .addComponent(CompararButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(EstadisticasButton)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompactarButton)
                    .addComponent(DescompactarButton)
                    .addComponent(CompararButton)
                    .addComponent(EstadisticasButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CompactarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompactarButtonMousePressed
        PanelGUIHandler.getInstance().changePanel(PanelGUIHandler.PanelCompactar);
    }//GEN-LAST:event_CompactarButtonMousePressed

    private void DescompactarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescompactarButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescompactarButtonMousePressed

    private void CompararButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompararButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompararButtonMousePressed

    private void EstadisticasButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasButtonMousePressed

    @Override
    public void init() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompactarButton;
    private javax.swing.JButton CompararButton;
    private javax.swing.JButton DescompactarButton;
    private javax.swing.JButton EstadisticasButton;
    // End of variables declaration//GEN-END:variables
}
