/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import Hamming.HammingProcessor;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author franc
 */
public class ProtegerPanel extends Panel {
    
    private String path,name;
    private boolean selected;
    File file;
    private HammingProcessor hm;
    /**
     * Creates new form ProtegerPanel
     */
    public ProtegerPanel() {
        initComponents();
        hm= new HammingProcessor();
    }
    @Override
    public void init() {
       textoArchivoTextArea.setText("");
       selected=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protegerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        protegerErrorButton = new javax.swing.JButton();
        protegerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        blockSizeComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArchivoTextArea = new javax.swing.JTextArea();
        proteger2ErroresButton = new javax.swing.JButton();
        probabilidadTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        protegerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        protegerLabel.setText("PROTEGER");

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirAButtonMousePressed(evt);
            }
        });
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        protegerErrorButton.setText("Proteger c/errores");
        protegerErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protegerErrorButtonMousePressed(evt);
            }
        });

        protegerButton.setText("Proteger s/errores");
        protegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protegerButtonMousePressed(evt);
            }
        });

        jLabel1.setText("Tamaño de bloque");

        blockSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "4096", "65536" }));
        blockSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockSizeComboBoxActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);
        jScrollPane1.setViewportView(textoArchivoTextArea);

        proteger2ErroresButton.setText("Proteger c/2errores");
        proteger2ErroresButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proteger2ErroresButtonMousePressed(evt);
            }
        });

        jLabel3.setText("Probabilidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(abrirAButton)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(blockSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proteger2ErroresButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(protegerErrorButton)
                                .addGap(152, 152, 152)
                                .addComponent(protegerButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(probabilidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(297, Short.MAX_VALUE))
            .addComponent(protegerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protegerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abrirAButton)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(blockSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protegerErrorButton)
                    .addComponent(protegerButton))
                .addGap(31, 31, 31)
                .addComponent(proteger2ErroresButton)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(probabilidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed
    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void protegerErrorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerErrorButtonMousePressed
        if (selected){
            int aux =1;
            hm.setBlockSize(Integer.parseInt(blockSizeComboBox.getItemAt(blockSizeComboBox.getSelectedIndex())));
            try {
                try{
                     aux = Integer.parseInt(probabilidadTextField.getText());
                }
                catch (NumberFormatException nme){
                    //TODO agregar el joptionPane(robarlo de IDS2)
                }
                hm.RHIEaS(path,aux);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_protegerErrorButtonMousePressed

    private void protegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerButtonMousePressed
        if (selected){
            hm.setBlockSize(Integer.parseInt(blockSizeComboBox.getItemAt(blockSizeComboBox.getSelectedIndex())));
            try {
                hm.RHaS(path);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_protegerButtonMousePressed

    private void abrirAButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirAButtonMousePressed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            selected =true;
            path = j.getSelectedFile().getAbsolutePath();
            file= new File(path);
            name = j.getSelectedFile().getName();
            name = name.substring(0, name.lastIndexOf('.'));
            try {
                String s = "", cadena = "";
                FileReader f = new FileReader(path);
                BufferedReader b = new BufferedReader(f);

                while ((cadena = b.readLine()) != null) {
                    s += cadena + "\n";
                }
                b.close();
                f.close();
                textoArchivoTextArea.setText(s);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CompactarPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            selected =false;
        }
    }//GEN-LAST:event_abrirAButtonMousePressed

    private void blockSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockSizeComboBoxActionPerformed
    }//GEN-LAST:event_blockSizeComboBoxActionPerformed

    private void proteger2ErroresButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteger2ErroresButtonMousePressed
            if (selected){
                int aux=1;
                hm.setBlockSize(Integer.parseInt(blockSizeComboBox.getItemAt(blockSizeComboBox.getSelectedIndex())));
                try {
                    try{
                        aux = Integer.parseInt(probabilidadTextField.getText());
                    }
                    catch(NumberFormatException nme){
                        //TODO agregar el joptionpane(robarlo de IDS2)
                        System.out.println("error");
                    }
                    hm.RHI2EaS(path,aux);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
        }
       
    }//GEN-LAST:event_proteger2ErroresButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JComboBox<String> blockSizeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField probabilidadTextField;
    private javax.swing.JButton proteger2ErroresButton;
    private javax.swing.JButton protegerButton;
    private javax.swing.JButton protegerErrorButton;
    private javax.swing.JLabel protegerLabel;
    private javax.swing.JTextArea textoArchivoTextArea;
    // End of variables declaration//GEN-END:variables

    
    
}
