/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author franc
 */
public class ProtegerPanel extends Panel {
    
    private String path;
    private boolean opened;
    File file; 

    /**
     * Creates new form ProtegerPanel
     */
    public ProtegerPanel() {
        initComponents();
    }
    @Override
    public void init() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protegerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirAButton = new javax.swing.JButton();
        textoArchivoTextArea = new javax.swing.JTextArea();
        protegerErrorButton = new javax.swing.JButton();
        archivoLabel = new javax.swing.JLabel();
        protegerButton = new javax.swing.JButton();

        protegerLabel.setText("Proteger");

        jLabel2.setText("Seleccionar archivo: ");

        abrirAButton.setText("Abrir Archivo");
        abrirAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAButtonActionPerformed(evt);
            }
        });

        textoArchivoTextArea.setColumns(20);
        textoArchivoTextArea.setRows(5);

        protegerErrorButton.setText("Proteger c/errores");
        protegerErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protegerErrorButtonMousePressed(evt);
            }
        });

        protegerButton.setText("Proteger s/errores");
        protegerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protegerButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(protegerLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(116, 116, 116)
                                .addComponent(abrirAButton)
                                .addGap(32, 32, 32)
                                .addComponent(archivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(protegerErrorButton)
                        .addGap(152, 152, 152)
                        .addComponent(protegerButton)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(protegerLabel)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abrirAButton)
                        .addComponent(jLabel2))
                    .addComponent(archivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textoArchivoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protegerErrorButton)
                    .addComponent(protegerButton))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = j.showSaveDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {
            opened=true;
            path = j.getSelectedFile().getAbsolutePath();
            archivoLabel.setText(path);
            file= new File(path);
        }
        else {
            archivoLabel.setText("No se cargo nada");
            opened=false;
        }
    }//GEN-LAST:event_abrirAButtonActionPerformed

    private void protegerErrorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerErrorButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_protegerErrorButtonMousePressed

    private void protegerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_protegerButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirAButton;
    private javax.swing.JLabel archivoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton protegerButton;
    private javax.swing.JButton protegerErrorButton;
    private javax.swing.JLabel protegerLabel;
    private javax.swing.JTextArea textoArchivoTextArea;
    // End of variables declaration//GEN-END:variables

    
    
}
